### PR TITLE
Destroy events from CKEditor5Integration when CK5 is destroyed

### LINKED ISSUE #459: CKEditor 5 integration is leaking memory
## Description

Hi, I'm a core developer of CKEditor 5 👋 

I'd like to inform you that the `MathType` plugin for the CKEditor 5 retains (lots of) memory when the editor is destroyed. This has been brought to our team's attention by our community and causes issues with integrations that re-start the editor a lot and/or use lots of editor instances on the same page.

## Environment

* Version: `"@wiris/mathtype-ckeditor5": "^7.24.0",`
* CKEditor 5
* Tested in Chrome on Mac

## Steps to reproduce

1. Close all Chrome windows.
2. Run Chrome with a guest profile (free of add-ons, etc.), on Mac this would be `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --guest --js-flags="--expose-gc"`
3. Configure CKEditor 5 **without** `MathType`.
4. Initialize the editor, then destroy it a couple of times. **Click the Garbage Collector button after each destruction**. Make sure no references are left behind (such as `window.editor`).
5. Take a memory snapshot.
6. Repeat 4.-5. a couple of times.
7. Configure CKEditor 5 **with** `MathType` enabled.
8. Repeat 4.-5. a couple of times.

## Expected result

There should be no dramatic difference in snapshot size and retained memory.

## Actual result

The presence of the `MathType` causes the editor to leak memory which is retained after each destruction.

Screenshot 2021-11-04 at 09 50 46

## Other details

Related issues in CKEditor 5:
* https://github.com/ckeditor/ckeditor5/issues/10749
* https://github.com/ckeditor/ckeditor5/issues/5954

### PR DESCRIPTION
**Pull request by icaparros-at-wiris**
## Description

Implemented the inherited `destroy?(): void` function on `plugin.js` file from `packages/mathtype-ckeditor5`, in order to remove all event listeners from the CKEditor5Integration object when CKEditor5 is destroyed. Remove the event listeners allow the garbatge collector free up the memory of the CKEditor5Integrations object.

## Steps to reproduce

1. Close all Chrome windows.
2. Run html5 CKEditor5 demo with a guest profile.
3. Initialize the editor, then destroy it a couple of times. Click the Garbage Collector button after each destruction. Make sure no references are left behind (such as window.editor).
4. Take a memory snapshot.
5. Repeat 3.-4. a couple of times.

## Expected result

There should be no dramatic difference in snapshot size and retained memory.

---

Closes #459 
[#taskid 17299](https://wiris.kanbanize.com/ctrl_board/2/cards/17299/details/)

### CODE REVIEW

**Review by xripoll-at-wiris — APPROVED** [review]

File: packages/mathtype-html-integration-devkit/src/integrationmodel.js [hunk 1]
```diff
@@ -387,6 +387,14 @@ export default class IntegrationModel {
     );
   }
 
+  /**
+   * Remove events to formulas in the DOM target.
```
Comment (carla-at-wiris) [inline packages/mathtype-html-integration-devkit/src/integrationmodel.js:391]: Does it mean we remove all the events created by mathtype for the formulas?

**Review by carla-at-wiris — COMMENTED** [review]
Apart from the `removeEvents()` function description i don't quite understand, everything looks splendid. Great work!

**Review by carla-at-wiris — CHANGES_REQUESTED** [review]
This task is included on the Q4 bug-sprint, so the Pull request needs to be done to the branch we have assignaed for the sprint: `KB-15953-BUGSPRINT ` instead of the `master` one.

**Comment by dcanet-at-wiris** [comment]
@icaparros-at-wiris @carla-at-wiris I've set this Pull request to the right target branch; the bug sprint one.

File: packages/mathtype-html-integration-devkit/src/integrationmodel.js (hunk 1 above)
Comment (icaparros-at-wiris) [reply packages/mathtype-html-integration-devkit/src/integrationmodel.js:391]: That's it. This function, it is called when CK5 is destroyed, and remove:

- dblClick, mouseDown, mouseUp event from eventTarget.
- mouseUp event from document.

These four events are added each time that CK5 with MathType is created. If we don't remove them each time that CK5 it is destroyed, the garbage collector will not destroy the CKEditor5Integration object.

**Review by carla-at-wiris — APPROVED** [review]
Looks great for me

**Review by dcanet-at-wiris — APPROVED** [review]
